OLED_ENABLE = yes
OLED_DRIVER = SSD1306
NKRO_ENABLE = yes
EXTRAKEY_ENABLE = yes
BOOTMAGIC_ENABLE = no
WPM_ENABLE = yes

CFLAGS += -flto
EXTRAFLAGS += -flto
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes